version: '3'
services:
  jupyter:
    image: igrantio/jupyter:0.0.2
    ports:
      - 8888:8888
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token=''
    platform: linux/amd64